# Generated by Django 5.1.3 on 2024-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='birdlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('scientificName', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('birdUrl', models.URLField()),
            ],
        ),
    ]
